#We use node.js libraries of tools for testing, building and automating React applications.
language: node_js

node_js:
  - 14

before_install:

#install yarn package and firebase tools.
- curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
# - yarn global add firebase-tools
- npm install -g firebase-tools

#Check for the JSON files for the content.
- rm -r ./src/JSONFolder
- mkdir ./src/JSONFolder
- curl -L -o ./src/JSONFolder/HtmlTopic-EN.json "https://onedrive.live.com/download?cid=20ECFD6F4F7D29C9&resid=20ECFD6F4F7D29C9%212466&authkey=AKPlIf4cJh_c7VY"
- curl -L -o ./src/JSONFolder/HtmlTopic-FR.json "https://onedrive.live.com/download?cid=20ECFD6F4F7D29C9&resid=20ECFD6F4F7D29C9%212464&authkey=ANDNjqyUhXwPGf0"
- curl -L -o ./src/JSONFolder/HtmlTest-FR.json "https://onedrive.live.com/download?cid=20ECFD6F4F7D29C9&resid=20ECFD6F4F7D29C9%212465&authkey=AFrWauhRwnsrExw"
- curl -L -o ./src/JSONFolder/HtmlTest-EN.json "https://onedrive.live.com/download?cid=20ECFD6F4F7D29C9&resid=20ECFD6F4F7D29C9%212463&authkey=ACSC6LB9LSVX3DQ"
- curl -L -o ./src/JSONFolder/FilterTopic-EN.json "https://onedrive.live.com/download?cid=20ECFD6F4F7D29C9&resid=20ECFD6F4F7D29C9%212462&authkey=AE4wxYTi-v_tgxc"
- curl -L -o ./src/JSONFolder/FilterTopic-FR.json "https://onedrive.live.com/download?cid=20ECFD6F4F7D29C9&resid=20ECFD6F4F7D29C9%212461&authkey=AE4byXCwdFuSoqg"

#install the dependencies (mentioned in yarn.lock file) with the right versions.
install:
- yarn install
- CI=false yarn build

#caching the modules required for node.
cache:
  directories:
  - node_modules

#deploying the web app by running commands from deploy.sh file whenever code is merged in master branch
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: 
    - master
