#We use node.js libraries of tools for testing, building and automating React applications.
language: node_js

node_js:
  - 18

dist: focal

include: [.well-known]

before_install:
#install yarn package and firebase tools.
- curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
- yarn global add firebase-tools
# - npm install -g firebase-tools
#Check for the JSON files for the content.

- rm -r ./src/JSONFolder
- mkdir ./src/JSONFolder
- curl -L -o ./src/JSONFolder/HtmlTopic-EN.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=EYA0_P4gW7NOkHAGvjZLpwwBQlvTMYAnrFsP9QhzZvsoUg&e=OlefhO"
- curl -L -o ./src/JSONFolder/HtmlTopic-FR.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=EV2fA5dGeqRAmMfTIPt6HikBmPJ2kvKi-MRlI61N8fA_eQ&e=agp16e"
- curl -L -o ./src/JSONFolder/HtmlTest-FR.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=EYDV2TLG3oBOp8sCq0GG2esB42R38t0jJ3oXEk0he5NKPQ&e=rTKoOR"
- curl -L -o ./src/JSONFolder/HtmlTest-EN.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=ERRHeZSq6uZIo9ReG_v6nuUBH0fd9i3DqhnMZ5jdBelE2A&e=9EIzgi"
- curl -L -o ./src/JSONFolder/FilterTopic-EN.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=EUgo5j83WEhBikbsiBqCKMEBG37TjWpap5kfmTU6Ug_UJg&e=Sqi9wl"
- curl -L -o ./src/JSONFolder/FilterTopic-FR.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=ETYyB_DeQwBHhM-GiSVLYBgBf8g6hBa1ep4BvJ4wLgh5KQ&e=bcxBau"

#install the dependencies (mentioned in yarn.lock file) with the right versions.
install:
- yarn install
- CI=false yarn build

#caching the modules required for node.
cache:
  directories:
  - node_modules

env:
  FIREBASE_CLI_EXPERIMENTS: webframeworks

#deploying the web app by running commands from deploy.sh file whenever code is merged in master branch
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: 
    - master