name: CI/CD Pipeline

on:
  push:
    branches:
      # - test
      # Uncomment for production deployment
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-secrets.json

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Yarn and Firebase Tools
        run: |
          curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
          export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
          yarn global add firebase-tools

      - name: Prepare JSON Folder
        run: |
          rm -rf ./src/JSONFolder
          mkdir ./src/JSONFolder
          curl -L -o ./src/JSONFolder/HtmlTopic-EN.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=EdffKbqIEx1Dm0ZdNNszHjUBGw7frv7K99Y5oqByzFgofQ&e=AbL5Wa"
          curl -L -o ./src/JSONFolder/HtmlTopic-FR.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=ETHjYvHwHwxBqsCyzw7VSVYBv2_DZ7vB8alVozWcrmdZQA&e=2pG1XB"
          curl -L -o ./src/JSONFolder/HtmlTest-FR.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=EXuSu4nlw_lDjxEMuNX3VlABcZ-3QTQEZbwtj4HJaw1M_g&e=BqAD4F"
          curl -L -o ./src/JSONFolder/HtmlTest-EN.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=EVn7b2mkcD5AhUYA5T6xetwBHQHKIpeWSqwLrWp4k16iqg&e=VFyBeV"
          curl -L -o ./src/JSONFolder/FilterTopic-EN.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=EesuEU-3d6VOlmOimE6L7IEBFwKUjpDgG-KEb6XauHDiEw&e=hpVYs7"
          curl -L -o ./src/JSONFolder/FilterTopic-FR.json "https://uottawa-my.sharepoint.com/personal/pnikb070_uottawa_ca/_layouts/15/download.aspx?share=EdLr7PmlV2JBjlkFB-z_MP0BT0N_DVRFFIpBwcNj3IbQzQ&e=6gaj1D"

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: CI=false yarn build

      - name: Prepare Google Application Credentials
        shell: bash
        run: |
          echo '${{ secrets.DEV_GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}' > base64 --decode > "google-secrets.json"

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive

